### ISSUE TITLE
Version 0.2.0 won´t be backwards compatible

### ISSUE THREAD

**Issue by mayuso** [mayuso/JavaDataMining#22]

**Comment by massilva** [comment]
I cloned the maven version. But not work.

I tried:
```mvn clean install```

But throws error.

**Comment by mayuso** [comment]
I used `mvn package` and works for me.

I still need to learn more about maven. Problems with maven will be fixed before I release 0.2.0 this week.

**Comment by mayuso** [comment]
Can you open an issue with the error it throws? That would help me solve it.

**Comment by massilva** [comment]
Ok.

I run: ```mvn package``` and throws error 'Connection timed out' :

```
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building JavaDataMining 0.1.0
[INFO] ------------------------------------------------------------------------
Downloading: http://streamreasoning.org/maven/net/sourceforge/javaml/0.1.7/javaml-0.1.7.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2:13.030s
[INFO] Finished at: Sun Jan 17 16:20:01 BRT 2016
[INFO] Final Memory: 8M/102M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project JavaDataMining: Could not resolve dependencies for project com.github.mayuso:JavaDataMining:jar:0.1.0: Failed to collect dependencies for [net.sourceforge:javaml:jar:0.1.7 (compile), org.apache.poi:poi-ooxml:jar:3.13 (compile), org.apache.poi:poi:jar:3.13 (compile)]: Failed to read artifact descriptor for net.sourceforge:javaml:jar:0.1.7: Could not transfer artifact net.sourceforge:javaml:pom:0.1.7 from/to spantus (http://streamreasoning.org/maven/): Connection to http://streamreasoning.org refused: Connection timed out -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

**Comment by mayuso** [comment]
I had the same error yesterday. f324ec2 <- This commit solved it. Maybe you did not pull?

**Comment by massilva** [comment]
[My POM](https://dl.dropboxusercontent.com/u/31864583/pom.xml) file is equals the [f32ec2](https://github.com/mayuso/JavaDataMining/commit/f324ec23fb748ba7b1460ebab7c991dc1537dd2b)

**Comment by massilva** [comment]
What your maven version?
My version is: Apache Maven 3.0.5

**Comment by mayuso** [comment]
3.3.9

**Comment by massilva** [comment]
I'm having trouble with maven.

I followed the [installation instruction](https://maven.apache.org/download.cgi#Installation). 
When I run ``` mvn --version ```.
Throws error:
```Error: Could not find or load the main class org.codehaus.plexus.classworlds.launcher.Launcher ```

I am searching for solution.

**Comment by mayuso** [comment]
I downloaded maven for an ubuntu system I have. It downloaded 3.0.5 version by default and I tried `mvn package` and `mvn clean install`. Both worked just fine.
