### ISSUE TITLE
fuck off

### ISSUE THREAD

**Issue by norwack** [mayuso/JavaDataMining#28]
Stop adding Linus over and over you fucking retard

**Comment by mayuso** [comment]
Already reported. Waiting response.

**Comment by norwack** [comment]
boohoo fucking retard, stop being an annoying little shit

**Comment by mayuso** [comment]
I don´t want to block you, stop please.

**Comment by norwack** [comment]
Stop adding Linus over and over then, you're spamming my notifications.

**Comment by mayuso** [comment]
Ok github, this was my last report. 3 ignored reports is enough. Im moving to BitBucket. BYE!

**Comment by norwack** [comment]
Wow you genuinely are retarded
