### ISSUE TITLE
Can you stop adding famous developers to your repos?

### ISSUE THREAD

**Issue by Qix-** [mayuso/JavaDataMining#29]
<img width="422" alt="screen shot 2016-01-19 at 05 16 01" src="https://cloud.githubusercontent.com/assets/885648/12418307/c2d54e94-be6b-11e5-8414-db9a9f6da199.png">

Usually I don't get 'meta' on Github but adding people like Linus Torvalds and Paul Irish to all of your repositories not only _doesn't_ get your code any more popularity, but it adds an air of cheapness and desperation to the project.

Not only that, but it causes such individuals whom already receive hundreds of notifications a day even more fluff to sort through, and ultimately causes more headache and wasted time that should be put forth to projects that really need it. Further, [I don't think Paul Irish really likes Java that much](http://www.paulirish.com/2007/fuck-you-java/), which makes adding him even less fruitful.

Also, before it's brought up, this is not the first time I've seen this happen. This is just the first time I'm choosing to say something about it.

Thank you for keeping Github a little cleaner!

**Comment by mayuso** [comment]
You are welcome.

**Comment by Qix-** [comment]
Code doesn't say alive by being popular, it stays alive by being useful and having maintainers that actively work on it.

Abusing the fact Github doesn't require confirmation upon adding users to repositories is directly abusing the open source community. Think about that next time.

**Comment by mayuso** [comment]
I prefer to get 100 stars and attention to my project than making an amazing API for literally no one.

**Comment by Qix-** [comment]
Then in my humble opinion you're coding for the wrong reasons. Useful code normally gets attention. Publish to package managers, introduce it to other projects via pull requests, etc.

**Comment by mayuso** [comment]
Can you then tell me reasons to code?

**Comment by Qix-** [comment]
Even though that's a baited question, there are loads of reasons. Fame shouldn't be one of them.

**Comment by mayuso** [comment]
Ok, seriously now, I realised that what I am doing is stupid, I will stop. Sorry.

**Comment by mayuso** [comment]
I started coding as a way of giving back to the Open Source community for offering code for free. I know see this was an error, will stop helping Open Source projects and only use their software for free, there is not reason to keep coding if no one wants my code.
I tried and Open Source community did not want my work, so I don´t feel bad with myself, I did all I could. I can now use code for free without feeling guilty. Thank you, and seriously, sorry.

**Comment by Qix-** [comment]
That's not the point here. The point is open source development isn't about having famous code. It's about open collaboration. Coders new to the open source community are always welcome, and I don't intend for this to discourage you from collaborating at all.

However, there are better ways to garner contributions to your own code. Developers that gain attention and followers are developers that have worked at it and have continually contributed and put forth time and effort into improving not only their own code, but others'.

Code being free is a side effect to all of that.

There isn't a golden formula to having popular code. The original point was to encourage other means of attracting contribution than to hinge off of the popularity and namesake of other developers. That's it.

**Comment by mayuso** [comment]
> Coders new to the open source community

I´m not, I hope others are so you guys can keep releasing free software. Good luck in your projects and bye :)
